import dotenv from "dotenv";
dotenv.config();

const {
	DISCORD_TOKEN,
	DISCORD_CLIENT_ID,
	DEFAULT_EVENT_DRAFT_CHANNEL_ID,
	DEFAULT_EVENT_PUBLISHING_DISCORD_CHANNEL_ID,
	DEFAULT_EVENT_PUBLISHING_VRC_CHANNEL_ID,
	isDev
} = process.env;

if (
	!DISCORD_TOKEN
	|| !DISCORD_CLIENT_ID
	|| !DEFAULT_EVENT_DRAFT_CHANNEL_ID
	|| !DEFAULT_EVENT_PUBLISHING_DISCORD_CHANNEL_ID
	|| !DEFAULT_EVENT_PUBLISHING_VRC_CHANNEL_ID
) {
	throw new Error("Missing environment variables");
}

export const config = {
	DISCORD_TOKEN,
	DISCORD_CLIENT_ID,
	DEFAULT_EVENT_DRAFT_CHANNEL_ID,
	DEFAULT_EVENT_PUBLISHING_DISCORD_CHANNEL_ID,
	DEFAULT_EVENT_PUBLISHING_VRC_CHANNEL_ID,
	isDev
};
